version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    restart: always
    environment: 
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data 
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.0
    restart: always
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601  
    

volumes:
  elasticsearch-data-volume:
    driver: local
networks:
  elastic:
    driver: bridge
