# Generated by Django 3.1 on 2022-11-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_chat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chat1',
        ),
    ]
